class ShortLinkError(Exception): ...


class DuplicateCodeError(ShortLinkError): ...


class LinkNotFoundError(ShortLinkError): ...


class InvalidUrlError(ShortLinkError): ...


class ExpiredLinkError(ShortLinkError): ...
