"""empty message

Revision ID: 151df46e4051
Revises: 06208ed69b66
Create Date: 2026-02-06 16:44:37.425002

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "151df46e4051"
down_revision: Union[str, Sequence[str], None] = "06208ed69b66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "link",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_url", sa.String(length=2048), nullable=False),
        sa.Column("short_code", sa.String(length=20), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_link_id"), "link", ["id"], unique=False)
    op.create_index(op.f("ix_link_owner_id"), "link", ["owner_id"], unique=False)
    op.create_index(op.f("ix_link_short_code"), "link", ["short_code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_link_short_code"), table_name="link")
    op.drop_index(op.f("ix_link_owner_id"), table_name="link")
    op.drop_index(op.f("ix_link_id"), table_name="link")
    op.drop_table("link")
    # ### end Alembic commands ###
