"""empty message

Revision ID: b09305658072
Revises: f24083d1af5e
Create Date: 2026-02-08 11:25:56.585233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b09305658072'
down_revision: Union[str, Sequence[str], None] = 'f24083d1af5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_session_id'), table_name='session')
    op.drop_table('session')
    op.drop_index(op.f('ix_link_id'), table_name='link')
    op.drop_index(op.f('ix_link_owner_id'), table_name='link')
    op.drop_index(op.f('ix_link_short_code'), table_name='link')
    op.drop_table('link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('original_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('short_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('clicks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('link_pkey'))
    )
    op.create_index(op.f('ix_link_short_code'), 'link', ['short_code'], unique=True)
    op.create_index(op.f('ix_link_owner_id'), 'link', ['owner_id'], unique=False)
    op.create_index(op.f('ix_link_id'), 'link', ['id'], unique=False)
    op.create_table('session',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('expires_data', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('session_pkey'))
    )
    op.create_index(op.f('ix_session_id'), 'session', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('nickname', name=op.f('user_nickname_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    # ### end Alembic commands ###
