"""empty message

Revision ID: f24083d1af5e
Revises: 151df46e4051
Create Date: 2026-02-06 17:38:24.641601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24083d1af5e'
down_revision: Union[str, Sequence[str], None] = '151df46e4051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'clicks')
    # ### end Alembic commands ###
