from typing import Protocol
from src.models.link import Link


class CodeGeneratorPort(Protocol):
    def generate(self) -> str: ...


class LinkRepositoryPort(Protocol):
    def create(self, link: Link) -> Link: ...
    def get_by_short_code(self, short_code: str) -> Link | None: ...
    def deactivate(self, link: Link) -> None: ...
    ...
