from typing import Protocol, List
from src.models.link import Link


class LinkRepositoryPort(Protocol):
    async def create(self, link: Link) -> Link: ...
    async def get_by_short_code(self, short_code: str) -> Link | None: ...
    async def deactivate(self, link: Link) -> None: ...
    async def get_by_user_id(self, user_id, offset: int, limit: int) -> List[Link]: ...
