from typing import Protocol

from src.schemas.link import LinkSchemaFull, LinkSchemaAdd, LinkResponse, LinkSchemaBase, LinksListResponse
from src.schemas.user import UserSchemaBase


class LinkRepositoryPort(Protocol):
    async def create(self, link: LinkSchemaAdd) -> LinkSchemaFull: ...
    async def deactivate(self, link: LinkSchemaBase) -> None: ...

    async def get_by_short_code(self, short_code: str) -> LinkResponse | None: ...
    async def get_by_user_id(self, user: UserSchemaBase, offset: int, limit: int) -> LinksListResponse: ...
