"""empty message

Revision ID: 9adff9456ab1
Revises: 3393006d1dee
Create Date: 2026-01-16 22:20:23.632638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9adff9456ab1'
down_revision: Union[str, Sequence[str], None] = '3393006d1dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('link', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_link_owner_id'), 'link', ['owner_id'], unique=False)
    op.drop_column('link', 'is_deleted')
    op.drop_column('link', 'expired_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('expired_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('link', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_link_owner_id'), table_name='link')
    op.drop_column('link', 'expires_at')
    op.drop_column('link', 'owner_id')
    # ### end Alembic commands ###
