"""empty message

Revision ID: bfc01a51e246
Revises: 9adff9456ab1
Create Date: 2026-01-26 14:57:37.912298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc01a51e246'
down_revision: Union[str, Sequence[str], None] = '9adff9456ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=300), nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
