# Общие ошибки приложения
class AppError(Exception): ...


# Ошибки, специфичные для модуля сокращения ссылок
class ShortLinkError(Exception): ...
class DuplicateCodeError(ShortLinkError): ...
class LinkNotFoundError(ShortLinkError): ...
class InvalidUrlError(ShortLinkError): ...
class ExpiredLinkError(ShortLinkError): ...



class AuthError(Exception): ...
class UserAlreadyExistsError(Exception): ...
